services:
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    container_name: innoclinic_rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped
  
  innoclinic-blob-storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: innoclinic.blob-storage
    volumes: 
      - ./.containers/blob_storage/data:/data
    ports:
      - "10000:10000"
    command: "azurite-blob --blobHost 0.0.0.0 -l /data --skipApiVersionCheck"

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.7
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
    volumes:
      - ./containers/identity:/opt/keycloak/data
    ports:
      - "8080:8080"
      - "9000:9000"
    command: start-dev
    user: root 

  gateway-api:
    container_name: innoclinic.gateway-api
    build:
      context: E:\Projects\GatewayAPI
      dockerfile: Dockerfile
    ports:
     - "7160:8081" 
     - "5137:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080

  profiles-api:
    container_name: innoclinic.profiles-api
    build:
      context: E:\InnoClinic.ProfilesAPI
      dockerfile: Dockerfile
      args:
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - GITHUB_PASSWORD=${GITHUB_PASSWORD}
    ports:
     - "7262:8081" 
     - "5154:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025" 
      - "1025:1025" 