services:
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    container_name: innoclinic_rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RabbitMQ__Host: ${RABBITMQ_HOST}
      RabbitMQ__Username: ${RABBITMQ_USERNAME}
      RabbitMQ__Password: ${RABBITMQ_PASSWORD}
    restart: unless-stopped
  
  innoclinic-blob-storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: innoclinic.blob-storage
    volumes: 
      - ./.containers/blob_storage/data:/data
    ports:
      - "10000:10000"
    command: "azurite-blob --blobHost 0.0.0.0 -l /data --skipApiVersionCheck"

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.7
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
    volumes:
      - ./containers/identity:/opt/keycloak/data
    ports:
      - "8080:8080"
      - "9000:9000"
    command: start-dev
    user: root 

  gateway-api:
    container_name: innoclinic.gateway-api
    build:
      context: E:\Projects\GatewayAPI
      dockerfile: Dockerfile
    ports:
     - "7160:8081" 
     - "5137:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - services-api
      - profiles-api
      - offices-api
      - appointments-api 
      - documents-api


  profiles-api:
    container_name: innoclinic.profiles-api
    build:
      context: E:\InnoClinic.ProfilesAPI
      dockerfile: Dockerfile
      args:
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - GITHUB_PASSWORD=${GITHUB_PASSWORD}
    ports:
     - "7262:8081" 
     - "5154:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - Authentication__MetadataAddress=http://keycloak:8080/realms/InnoClinic/.well-known/openid-configuration
      - ConnectionStrings__DefaultConnection=${PROFILES_DB_CONNECTION_STRING}
      - RabbitMQ__Host=${RABBITMQ_HOST}
      - RabbitMQ__Username=${RABBITMQ_USERNAME}
      - RabbitMQ__Password=${RABBITMQ_PASSWORD}

  services-api:
    container_name: innoclinic.services-api
    build:
      context: E:\ServicesAPIgit
      dockerfile: Dockerfile
      args:
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - GITHUB_PASSWORD=${GITHUB_PASSWORD}   
    ports:
     - "7278:8081" 
     - "5095:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - Authentication__MetadataAddress=http://keycloak:8080/realms/InnoClinic/.well-known/openid-configuration
      - ConnectionStrings__DefaultConnection=${SERVICES_DB_CONNECTION_STRING}
      - RabbitMQ__Host=${RABBITMQ_HOST}
      - RabbitMQ__Username=${RABBITMQ_USERNAME}
      - RabbitMQ__Password=${RABBITMQ_PASSWORD}
      
  appointments-api:
      container_name: innoclinic.appointments-api
      build:
        context: E:\Innowise Project\AppointmentsAPI
        dockerfile: Dockerfile 
        args:
        - GITHUB_USERNAME=${GITHUB_USERNAME}
        - GITHUB_PASSWORD=${GITHUB_PASSWORD}
      ports:
       - "7039:8081" 
       - "5203:8080"
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        - Authentication__MetadataAddress=http://keycloak:8080/realms/InnoClinic/.well-known/openid-configuration
        - ConnectionStrings__DefaultConnection=${APPOINTMENTS_DB_CONNECTION_STRING}
        - RabbitMQ__Host=${RABBITMQ_HOST}
        - RabbitMQ__Username=${RABBITMQ_USERNAME}
        - RabbitMQ__Password=${RABBITMQ_PASSWORD}

  offices-api:
      container_name: innoclinic.offices-api
      build:
        context: E:\Innowise Project\OfficesAPI\InnoClinic.OfficesApi
        dockerfile: Dockerfile 
        args:
        - GITHUB_USERNAME=${GITHUB_USERNAME}
        - GITHUB_PASSWORD=${GITHUB_PASSWORD}
      ports:
       - "7169:8081" 
       - "5193:8080"
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        - Authentication__MetadataAddress=http://keycloak:8080/realms/InnoClinic/.well-known/openid-configuration
        - OfficeDatabaseSettings__ConnectionString=${OFFICES_DB_CONNECTION_STRING}
        - OfficeDatabaseSettings__DatabaseName=OfficesDb
        - OfficeDatabaseSettings__OfficesCollectionName=Offices
        - RabbitMQ__Host=${RABBITMQ_HOST}
        - RabbitMQ__Username=${RABBITMQ_USERNAME}
        - RabbitMQ__Password=${RABBITMQ_PASSWORD}

  documents-api:
    container_name: innoclinic.documents-api
    build:
      context: E:\Projects\DocumentsAPI 
      dockerfile: Dockerfile 
      args:
        - GITHUB_USERNAME=${GITHUB_USERNAME}
        - GITHUB_PASSWORD=${GITHUB_PASSWORD}
    ports:
      - "7266:8081" 
      - "5105:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - Authentication__MetadataAddress=http://keycloak:8080/realms/InnoClinic/.well-known/openid-configuration
      - ConnectionStrings__BlobStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://innoclinic-blob-storage:10000/devstoreaccount1;
      - RabbitMQ__Host=${RABBITMQ_HOST} 
      - RabbitMQ__Username=${RABBITMQ_USERNAME}
      - RabbitMQ__Password=${RABBITMQ_PASSWORD}
  
  mailpit: 
    image: axllent/mailpit
    ports:
      - "8025:8025" 
      - "1025:1025" 